title: Electronic Component Classification
# description: >- # this means to ignore newlines until "baseurl:"
#   Blog post about the classification of electronic components from
#   hand drawn sketches.

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme